name: SKWarpgate
version: 1.0
author: Alfred Sporre
main: com.sk.warpgate.SKMain

commands:
    skwarpgate:
        description: Displays general information
        usage: /skwarpgate
        aliases: skwg
    skwarpgate list:
        description: Lists all your warpgates
        usage: /skwarpgate list
    skwarpgate bind:
        description: Binds two warpgates
        usage: /skwarpgate bind <warpgate1> <warpgate2>